name: Build Debug Dylib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set active Xcode path
        run: |
          XCODE_VERSION=$(cat versions.json | python3 -c 'import json,sys;obj=json.load(sys.stdin);print(obj["xcode"]);')
          sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app/Contents/Developer

      - name: Compile dylib
        run: |
          mkdir -p build
          clang -dynamiclib -arch arm64 \
            -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
            -framework Foundation -framework UIKit \
            tools/ReynardGramDebug.m -o build/ReynardGramDebug.dylib

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReynardGramDebug-dylib
          path: build/ReynardGramDebug.dylib
